import type { CuisineKey } from "./cuisine";

/** Multilingual string. `en` is the canonical fallback; other locale keys may or may not exist.
 *  The seeder picks `[seedLocale]` and falls back to `en` when missing. */
export type LocaleString = { en: string } & Partial<Record<string, string>>;

export type SeedCategory = { sortOrder: number; name: LocaleString };

export type SeedItem = {
  categoryIndex: number;
  sortOrder: number;
  price: number;
  name: LocaleString;
  description?: LocaleString;
  /** Direct S3 URL — reused from the previously generated template image set. */
  imageUrl?: string;
};

export type CuisineTemplate = {
  subtitle: LocaleString;
  categories: SeedCategory[];
  items: SeedItem[];
  /** Restaurant cover background. */
  backgroundUrl?: string;
};

const COMMON_PLACEHOLDERS = {
  description: {
    en: "Replace this with your own description",
    es: "Reemplaza esto con tu descripción",
    de: "Ersetze dies durch deine eigene Beschreibung",
    fr: "Remplace ceci par ta propre description",
    it: "Sostituisci con la tua descrizione",
    pt: "Substitui por tua descrição",
    nl: "Vervang dit door je eigen beschrijving",
    pl: "Zastąp to własnym opisem",
    ru: "Замени это своим описанием",
    uk: "Заміни це своїм описом",
    sv: "Ersätt detta med din egen beskrivning",
    da: "Erstat dette med din egen beskrivelse",
    no: "Erstatt dette med din egen beskrivelse",
    fi: "Korvaa tämä omalla kuvauksellasi",
    cs: "Nahraď to vlastním popisem",
    el: "Αντικαταστήστε με τη δική σας περιγραφή",
    tr: "Bunu kendi açıklamanla değiştir",
    ro: "Înlocuiește cu propria descriere",
    hu: "Cseréld le saját leírásra",
    bg: "Замени това със собственото си описание",
    hr: "Zamijeni vlastitim opisom",
    sk: "Nahraď vlastným popisom",
    sl: "Zamenjaj s svojim opisom",
    et: "Asenda oma kirjeldusega",
    lv: "Aizstāj ar savu aprakstu",
    lt: "Pakeisk savo aprašymu",
    sr: "Zameni sopstvenim opisom",
    ca: "Substitueix per la teva descripció",
    ga: "Athchuir é seo le do thuairisc féin",
    is: "Skiptu þessu út fyrir þína eigin lýsingu",
    fa: "این را با توضیحات خودتان جایگزین کنید",
    ar: "استبدل هذا بوصفك الخاص",
    ja: "ここをあなたの説明に置き換えてください",
    ko: "이것을 자신의 설명으로 바꾸세요",
    zh: "将此处替换为您自己的描述",
  } as LocaleString,
  address: "Sample Street 1, Your City",
  phone: "+34 600 000 000",
  instagram: "your_restaurant",
  whatsapp: "+34600000000",
};

export const commonPlaceholders = COMMON_PLACEHOLDERS;

/** Default restaurant name applied to every brand-new account (onboarding is
 *  currently skipped, so the cuisine/name steps never run). Localized so the
 *  seeded restaurant reads naturally in the user's language. */
export const DEFAULT_RESTAURANT_NAME: LocaleString = {
  en: "My restaurant",
  es: "Mi restaurante",
  de: "Mein Restaurant",
  fr: "Mon restaurant",
  it: "Il mio ristorante",
  pt: "Meu restaurante",
  nl: "Mijn restaurant",
  pl: "Moja restauracja",
  ru: "Мой ресторан",
  uk: "Мій ресторан",
  sv: "Min restaurang",
  da: "Min restaurant",
  no: "Min restaurant",
  fi: "Ravintolani",
  cs: "Moje restaurace",
  el: "Το εστιατόριό μου",
  tr: "Restoranım",
  ro: "Restaurantul meu",
  hu: "Az éttermem",
  bg: "Моят ресторант",
  hr: "Moj restoran",
  sk: "Moja reštaurácia",
  sl: "Moja restavracija",
  et: "Minu restoran",
  lv: "Mans restorāns",
  lt: "Mano restoranas",
  sr: "Moj restoran",
  ca: "El meu restaurant",
  ga: "Mo bhialann",
  is: "Veitingastaðurinn minn",
  fa: "رستوران من",
  ar: "مطعمي",
  ja: "マイレストラン",
  ko: "내 레스토랑",
  zh: "我的餐厅",
};

/** Single universal template. Two categories (Food / Drinks), two items each.
 *  Food items carry a reused S3 photo; drinks intentionally have no image. */
export const cuisineTemplates: Record<CuisineKey, CuisineTemplate> = {
  restaurant: {
    subtitle: {
      en: "Fresh food & drinks",
      es: "Comida y bebidas frescas",
      de: "Frische Speisen & Getränke",
      fr: "Plats & boissons frais",
      it: "Cibo e bevande freschi",
      pt: "Comida e bebidas frescas",
      nl: "Vers eten & drinken",
      pl: "Świeże jedzenie i napoje",
      ru: "Свежая еда и напитки",
      uk: "Свіжа їжа та напої",
      sv: "Färsk mat & dryck",
      da: "Frisk mad & drikke",
      no: "Fersk mat og drikke",
      fi: "Tuoretta ruokaa ja juomaa",
      cs: "Čerstvé jídlo a nápoje",
      el: "Φρέσκο φαγητό & ποτά",
      tr: "Taze yemek & içecek",
      ro: "Mâncare și băuturi proaspete",
      hu: "Friss ételek és italok",
      bg: "Прясна храна и напитки",
      hr: "Svježa hrana i pića",
      sk: "Čerstvé jedlo a nápoje",
      sl: "Sveža hrana in pijača",
      et: "Värske toit ja joogid",
      lv: "Svaigs ēdiens un dzērieni",
      lt: "Šviežias maistas ir gėrimai",
      sr: "Sveža hrana i pića",
      ca: "Menjar i begudes fresques",
      ga: "Bia & deochanna úra",
      is: "Ferskur matur og drykkir",
      fa: "غذا و نوشیدنی تازه",
      ar: "طعام ومشروبات طازجة",
      ja: "新鮮な料理とドリンク",
      ko: "신선한 음식과 음료",
      zh: "新鲜美食与饮品",
    },
    categories: [
      {
        sortOrder: 1,
        name: {
          en: "Food",
          es: "Comida",
          de: "Speisen",
          fr: "Plats",
          it: "Cibo",
          pt: "Comida",
          nl: "Eten",
          pl: "Jedzenie",
          ru: "Еда",
          uk: "Їжа",
          sv: "Mat",
          da: "Mad",
          no: "Mat",
          fi: "Ruoka",
          cs: "Jídlo",
          el: "Φαγητό",
          tr: "Yemek",
          ro: "Mâncare",
          hu: "Ételek",
          bg: "Храна",
          hr: "Hrana",
          sk: "Jedlo",
          sl: "Hrana",
          et: "Toit",
          lv: "Ēdiens",
          lt: "Maistas",
          sr: "Hrana",
          ca: "Menjar",
          ga: "Bia",
          is: "Matur",
          fa: "غذا",
          ar: "طعام",
          ja: "料理",
          ko: "음식",
          zh: "美食",
        },
      },
      {
        sortOrder: 2,
        name: {
          en: "Drinks",
          es: "Bebidas",
          de: "Getränke",
          fr: "Boissons",
          it: "Bevande",
          pt: "Bebidas",
          nl: "Dranken",
          pl: "Napoje",
          ru: "Напитки",
          uk: "Напої",
          sv: "Drycker",
          da: "Drikkevarer",
          no: "Drikke",
          fi: "Juomat",
          cs: "Nápoje",
          el: "Ποτά",
          tr: "İçecekler",
          ro: "Băuturi",
          hu: "Italok",
          bg: "Напитки",
          hr: "Pića",
          sk: "Nápoje",
          sl: "Pijače",
          et: "Joogid",
          lv: "Dzērieni",
          lt: "Gėrimai",
          sr: "Pića",
          ca: "Begudes",
          ga: "Deochanna",
          is: "Drykkir",
          fa: "نوشیدنی‌ها",
          ar: "مشروبات",
          ja: "ドリンク",
          ko: "음료",
          zh: "饮品",
        },
      },
    ],
    items: [
      {
        categoryIndex: 0,
        sortOrder: 1,
        price: 9.5,
        imageUrl: "https://nbg1.your-objectstorage.com/sobogd/templates/dishes/sample-pizza.webp",
        name: {
          en: "Pizza",
          es: "Pizza",
          de: "Pizza",
          fr: "Pizza",
          it: "Pizza",
          pt: "Pizza",
          nl: "Pizza",
          pl: "Pizza",
          ru: "Пицца",
          uk: "Піца",
          sv: "Pizza",
          da: "Pizza",
          no: "Pizza",
          fi: "Pizza",
          cs: "Pizza",
          el: "Πίτσα",
          tr: "Pizza",
          ro: "Pizza",
          hu: "Pizza",
          bg: "Пица",
          hr: "Pizza",
          sk: "Pizza",
          sl: "Pica",
          et: "Pitsa",
          lv: "Pica",
          lt: "Pica",
          sr: "Pica",
          ca: "Pizza",
          ga: "Píotsa",
          is: "Pizza",
          fa: "پیتزا",
          ar: "بيتزا",
          ja: "ピザ",
          ko: "피자",
          zh: "披萨",
        },
        description: {
          en: "Tomato, mozzarella, prosciutto, arugula and parmesan",
          es: "Tomate, mozzarella, jamón, rúcula y parmesano",
          de: "Tomate, Mozzarella, Prosciutto, Rucola und Parmesan",
          fr: "Tomate, mozzarella, prosciutto, roquette et parmesan",
          it: "Pomodoro, mozzarella, prosciutto, rucola e parmigiano",
          pt: "Tomate, mozzarella, presunto, rúcula e parmesão",
          nl: "Tomaat, mozzarella, prosciutto, rucola en parmezaan",
          pl: "Pomidor, mozzarella, prosciutto, rukola i parmezan",
          ru: "Томаты, моцарелла, прошутто, руккола и пармезан",
          uk: "Томати, моцарела, прошуто, рукола та пармезан",
          sv: "Tomat, mozzarella, prosciutto, ruccola och parmesan",
          da: "Tomat, mozzarella, prosciutto, rucola og parmesan",
          no: "Tomat, mozzarella, prosciutto, ruccola og parmesan",
          fi: "Tomaatti, mozzarella, prosciutto, rucola ja parmesaani",
          cs: "Rajče, mozzarella, prosciutto, rukola a parmazán",
          el: "Ντομάτα, μοτσαρέλα, προσούτο, ρόκα και παρμεζάνα",
          tr: "Domates, mozzarella, jambon, roka ve parmesan",
          ro: "Roșii, mozzarella, prosciutto, rucola și parmezan",
          hu: "Paradicsom, mozzarella, prosciutto, rukkola és parmezán",
          bg: "Домати, моцарела, прошуто, рукола и пармезан",
          hr: "Rajčica, mozzarella, pršut, rikola i parmezan",
          sk: "Paradajka, mozzarella, prosciutto, rukola a parmezán",
          sl: "Paradižnik, mozzarella, pršut, rukola in parmezan",
          et: "Tomat, mozzarella, prosciutto, rukola ja parmesan",
          lv: "Tomāti, mocarella, prosciutto, rukola un parmezāns",
          lt: "Pomidorai, mocarela, prosciutto, gražgarstės ir parmezanas",
          sr: "Paradajz, mocarela, pršuta, rukola i parmezan",
          ca: "Tomàquet, mozzarella, pernil, ruca i parmesà",
          ga: "Trátaí, mozzarella, prosciutto, arúgula agus parmasáin",
          is: "Tómatur, mozzarella, prosciutto, klettasalat og parmesan",
          fa: "گوجه‌فرنگی، موزارلا، پروشوتو، روکولا و پارمزان",
          ar: "طماطم، موزاريلا، بروشوتو، جرجير وبارميزان",
          ja: "トマト、モッツァレラ、生ハム、ルッコラ、パルメザン",
          ko: "토마토, 모차렐라, 프로슈토, 루콜라, 파르메산",
          zh: "番茄、马苏里拉、帕尔玛火腿、芝麻菜和帕尔马干酪",
        },
      },
      {
        categoryIndex: 0,
        sortOrder: 2,
        price: 8.5,
        imageUrl: "https://nbg1.your-objectstorage.com/sobogd/templates/dishes/sample-caesar-salad.webp",
        name: {
          en: "Caesar Salad",
          es: "Ensalada César",
          de: "Caesar Salat",
          fr: "Salade César",
          it: "Insalata Caesar",
          pt: "Salada Caesar",
          nl: "Caesarsalade",
          pl: "Sałatka Cezar",
          ru: "Салат «Цезарь»",
          uk: "Салат «Цезар»",
          sv: "Caesarsallad",
          da: "Cæsarsalat",
          no: "Cæsarsalat",
          fi: "Caesar-salaatti",
          cs: "Caesar salát",
          el: "Σαλάτα του Καίσαρα",
          tr: "Sezar Salatası",
          ro: "Salată Caesar",
          hu: "Cézár saláta",
          bg: "Салата «Цезар»",
          hr: "Cezar salata",
          sk: "Caesar šalát",
          sl: "Cezar solata",
          et: "Caesari salat",
          lv: "Cēzara salāti",
          lt: "Cezario salotos",
          sr: "Cezar salata",
          ca: "Amanida Cèsar",
          ga: "Sailéad Caesar",
          is: "Caesar salat",
          fa: "سالاد سزار",
          ar: "سلطة سيزر",
          ja: "シーザーサラダ",
          ko: "시저 샐러드",
          zh: "凯撒沙拉",
        },
        description: {
          en: "Romaine, grilled chicken, parmesan, croutons and Caesar dressing",
          es: "Lechuga romana, pollo a la parrilla, parmesano, picatostes y aderezo César",
          de: "Römersalat, gegrilltes Hähnchen, Parmesan, Croutons und Caesar-Dressing",
          fr: "Romaine, poulet grillé, parmesan, croûtons et sauce César",
          it: "Lattuga romana, pollo grigliato, parmigiano, crostini e salsa Caesar",
          pt: "Alface romana, frango grelhado, parmesão, croutons e molho César",
          nl: "Romeinse sla, gegrilde kip, parmezaan, croutons en caesardressing",
          pl: "Sałata rzymska, grillowany kurczak, parmezan, grzanki i sos Cezar",
          ru: "Романо, курица гриль, пармезан, гренки и соус «Цезарь»",
          uk: "Романо, курка гриль, пармезан, грінки та соус «Цезар»",
          sv: "Romansallad, grillad kyckling, parmesan, krutonger och caesardressing",
          da: "Romainesalat, grillet kylling, parmesan, krutoner og caesardressing",
          no: "Romanosalat, grillet kylling, parmesan, krutonger og caesardressing",
          fi: "Roomansalaatti, grillattu kana, parmesaani, krutonkeja ja caesarkastike",
          cs: "Římský salát, grilované kuře, parmazán, krutony a caesar dresink",
          el: "Μαρούλι, ψητό κοτόπουλο, παρμεζάνα, κρουτόν και σος Caesar",
          tr: "Marul, ızgara tavuk, parmesan, kruton ve Sezar sosu",
          ro: "Salată romană, pui la grătar, parmezan, crutoane și sos Caesar",
          hu: "Római saláta, grillezett csirke, parmezán, kruton és Cézár öntet",
          bg: "Романо, пилешко на грил, пармезан, крутони и сос «Цезар»",
          hr: "Rimska salata, piletina s roštilja, parmezan, krutoni i Cezar preljev",
          sk: "Rímsky šalát, grilované kura, parmezán, krutóny a caesar dresing",
          sl: "Rimska solata, piščanec z žara, parmezan, krutoni in Cezar preliv",
          et: "Rooma salat, grillitud kana, parmesan, krutoonid ja Caesari kaste",
          lv: "Romiešu salāti, grilēta vista, parmezāns, grauzdiņi un Cēzara mērce",
          lt: "Romaninės salotos, kepta vištiena, parmezanas, skrudinta duona ir Cezario padažas",
          sr: "Rimska salata, piletina sa roštilja, parmezan, krutoni i Cezar preliv",
          ca: "Enciam romà, pollastre a la brasa, parmesà, crostons i amaniment Cèsar",
          ga: "Leitís Rómhánach, sicín gríoscaithe, parmasáin, crústaí agus anlann Caesar",
          is: "Romaine, grillaður kjúklingur, parmesan, brauðteningar og Caesar-sósa",
          fa: "کاهو رومی، مرغ گریل، پارمزان، نان برشته و سس سزار",
          ar: "خس روماني، دجاج مشوي، بارميزان، خبز محمص وصلصة سيزر",
          ja: "ロメインレタス、グリルチキン、パルメザン、クルトン、シーザードレッシング",
          ko: "로메인, 구운 치킨, 파르메산, 크루통, 시저 드레싱",
          zh: "罗马生菜、烤鸡、帕尔马干酪、面包丁和凯撒酱",
        },
      },
      {
        categoryIndex: 1,
        sortOrder: 1,
        price: 3.5,
        name: {
          en: "Orange Juice",
          es: "Zumo de naranja",
          de: "Orangensaft",
          fr: "Jus d'orange",
          it: "Succo d'arancia",
          pt: "Sumo de laranja",
          nl: "Sinaasappelsap",
          pl: "Sok pomarańczowy",
          ru: "Апельсиновый сок",
          uk: "Апельсиновий сік",
          sv: "Apelsinjuice",
          da: "Appelsinjuice",
          no: "Appelsinjuice",
          fi: "Appelsiinimehu",
          cs: "Pomerančový džus",
          el: "Χυμός πορτοκάλι",
          tr: "Portakal suyu",
          ro: "Suc de portocale",
          hu: "Narancslé",
          bg: "Портокалов сок",
          hr: "Sok od naranče",
          sk: "Pomarančový džús",
          sl: "Pomarančni sok",
          et: "Apelsinimahl",
          lv: "Apelsīnu sula",
          lt: "Apelsinų sultys",
          sr: "Sok od pomorandže",
          ca: "Suc de taronja",
          ga: "Sú oráiste",
          is: "Appelsínusafi",
          fa: "آب پرتقال",
          ar: "عصير برتقال",
          ja: "オレンジジュース",
          ko: "오렌지 주스",
          zh: "橙汁",
        },
        description: {
          en: "Freshly squeezed orange juice",
          es: "Zumo de naranja recién exprimido",
          de: "Frisch gepresster Orangensaft",
          fr: "Jus d'orange fraîchement pressé",
          it: "Succo d'arancia appena spremuto",
          pt: "Sumo de laranja acabado de espremer",
          nl: "Versgeperst sinaasappelsap",
          pl: "Świeżo wyciskany sok pomarańczowy",
          ru: "Свежевыжатый апельсиновый сок",
          uk: "Свіжовичавлений апельсиновий сік",
          sv: "Nypressad apelsinjuice",
          da: "Friskpresset appelsinjuice",
          no: "Nypresset appelsinjuice",
          fi: "Vastapuristettu appelsiinimehu",
          cs: "Čerstvě vymačkaný pomerančový džus",
          el: "Φρεσκοστυμμένος χυμός πορτοκάλι",
          tr: "Taze sıkılmış portakal suyu",
          ro: "Suc de portocale proaspăt stors",
          hu: "Frissen facsart narancslé",
          bg: "Прясно изцеден портокалов сок",
          hr: "Svježe cijeđeni sok od naranče",
          sk: "Čerstvo vylisovaný pomarančový džús",
          sl: "Sveže stisnjen pomarančni sok",
          et: "Värskelt pressitud apelsinimahl",
          lv: "Svaigi spiesta apelsīnu sula",
          lt: "Šviežiai spaustos apelsinų sultys",
          sr: "Sveže ceđeni sok od pomorandže",
          ca: "Suc de taronja acabat d'esprémer",
          ga: "Sú oráiste úrfháiscthe",
          is: "Nýkreistur appelsínusafi",
          fa: "آب پرتقال تازه",
          ar: "عصير برتقال طازج",
          ja: "搾りたてオレンジジュース",
          ko: "갓 짜낸 오렌지 주스",
          zh: "鲜榨橙汁",
        },
      },
      {
        categoryIndex: 1,
        sortOrder: 2,
        price: 2.8,
        name: {
          en: "Cappuccino",
          es: "Cappuccino",
          de: "Cappuccino",
          fr: "Cappuccino",
          it: "Cappuccino",
          pt: "Cappuccino",
          nl: "Cappuccino",
          pl: "Cappuccino",
          ru: "Капучино",
          uk: "Капучино",
          sv: "Cappuccino",
          da: "Cappuccino",
          no: "Cappuccino",
          fi: "Cappuccino",
          cs: "Cappuccino",
          el: "Καπουτσίνο",
          tr: "Kapuçino",
          ro: "Cappuccino",
          hu: "Cappuccino",
          bg: "Капучино",
          hr: "Cappuccino",
          sk: "Cappuccino",
          sl: "Cappuccino",
          et: "Kaputsiino",
          lv: "Kapučīno",
          lt: "Kapučino",
          sr: "Cappuccino",
          ca: "Cappuccino",
          ga: "Cappuccino",
          is: "Cappuccino",
          fa: "کاپوچینو",
          ar: "كابتشينو",
          ja: "カプチーノ",
          ko: "카푸치노",
          zh: "卡布奇诺",
        },
        description: {
          en: "Espresso with steamed milk foam",
          es: "Espresso con espuma de leche",
          de: "Espresso mit aufgeschäumter Milch",
          fr: "Espresso avec mousse de lait",
          it: "Espresso con schiuma di latte",
          pt: "Espresso com espuma de leite",
          nl: "Espresso met opgeschuimde melk",
          pl: "Espresso z mleczną pianką",
          ru: "Эспрессо со вспененным молоком",
          uk: "Еспресо зі спіненим молоком",
          sv: "Espresso med skummad mjölk",
          da: "Espresso med skummet mælk",
          no: "Espresso med skummet melk",
          fi: "Espresso ja maitovaahto",
          cs: "Espresso s mléčnou pěnou",
          el: "Εσπρέσο με αφρόγαλα",
          tr: "Süt köpüklü espresso",
          ro: "Espresso cu spumă de lapte",
          hu: "Espresso tejhabbal",
          bg: "Еспресо с разпенено мляко",
          hr: "Espresso s mliječnom pjenom",
          sk: "Espresso s mliečnou penou",
          sl: "Espresso z mlečno peno",
          et: "Espresso piimavahuga",
          lv: "Espresso ar piena putām",
          lt: "Espresso su pieno puta",
          sr: "Espresso s mlečnom penom",
          ca: "Espresso amb escuma de llet",
          ga: "Espresso le cúr bainne",
          is: "Espressó með mjólkurfroðu",
          fa: "اسپرسو با کف شیر",
          ar: "إسبريسو مع رغوة الحليب",
          ja: "エスプレッソとミルクフォーム",
          ko: "에스프레소와 우유 거품",
          zh: "浓缩咖啡配奶泡",
        },
      },
    ],
    backgroundUrl: "https://nbg1.your-objectstorage.com/sobogd/templates/backgrounds/sample-restaurant-interior.webp",
  },
};

// Pool of realistic guest names per locale, used to populate sample orders/reservations.
// Locales not listed fall back to "en" in the seeder.
export const sampleGuestNames: Record<string, string[]> = {
  en: ["John Smith", "Sarah Johnson", "Michael Brown", "Emma Davis", "David Wilson", "Olivia Taylor"],
  es: ["María García", "Carlos López", "Laura Martínez", "Javier Rodríguez", "Sofía Fernández", "Diego Ruiz"],
  de: ["Anna Müller", "Lukas Schmidt", "Sophie Weber", "Maximilian Fischer"],
  fr: ["Pierre Dubois", "Marie Lefèvre", "Julien Bernard", "Camille Moreau"],
  it: ["Giulia Rossi", "Marco Bianchi", "Chiara Russo", "Lorenzo Ferrari"],
  pt: ["João Silva", "Mariana Santos", "Pedro Costa", "Ana Oliveira"],
  nl: ["Jan de Vries", "Emma Bakker", "Lars Visser", "Sophie Jansen"],
  pl: ["Anna Kowalska", "Piotr Nowak", "Maria Wiśniewska", "Tomasz Wójcik"],
  ru: ["Иван Иванов", "Анна Петрова", "Дмитрий Смирнов", "Екатерина Соколова"],
  uk: ["Олександр Шевченко", "Олена Коваленко", "Андрій Мельник", "Наталія Бондар"],
  sv: ["Erik Andersson", "Anna Karlsson", "Lars Johansson", "Maja Lindberg"],
  da: ["Mads Nielsen", "Sofie Hansen", "Lars Pedersen", "Emma Larsen"],
  no: ["Lars Hansen", "Ingrid Olsen", "Erik Berg", "Emma Solberg"],
  fi: ["Mikko Korhonen", "Anna Virtanen", "Jukka Mäkinen", "Liisa Nieminen"],
  cs: ["Jan Novák", "Eva Svobodová", "Petr Dvořák", "Tereza Černá"],
  el: ["Γιώργος Παπαδόπουλος", "Ελένη Δημητρίου", "Νίκος Γεωργίου", "Μαρία Ιωάννου"],
  tr: ["Mehmet Yılmaz", "Ayşe Demir", "Ali Kaya", "Zeynep Çelik"],
  ro: ["Andrei Popescu", "Maria Ionescu", "Mihai Stan", "Elena Dumitrescu"],
  hu: ["Péter Nagy", "Anna Kovács", "István Tóth", "Eszter Szabó"],
  bg: ["Иван Петров", "Мария Иванова", "Георги Димитров", "Елена Стоянова"],
  hr: ["Ivan Horvat", "Ana Marić", "Marko Novak", "Petra Kovačević"],
  sk: ["Ján Novák", "Mária Kováčová", "Peter Horváth", "Zuzana Tóthová"],
  sl: ["Janez Novak", "Maja Kovač", "Luka Horvat", "Eva Krajnc"],
  et: ["Andres Tamm", "Kati Saar", "Toomas Mägi", "Liis Kask"],
  lv: ["Jānis Bērziņš", "Anna Liepa", "Pēteris Kalniņš", "Līga Ozola"],
  lt: ["Jonas Petraitis", "Eglė Kazlauskienė", "Tomas Jankauskas", "Rūta Stankevičiūtė"],
  sr: ["Marko Petrović", "Ana Jovanović", "Stefan Nikolić", "Jelena Đorđević"],
  ca: ["Jordi Puig", "Núria Vila", "Marc Soler", "Anna Roca"],
  ga: ["Seán Ó Briain", "Áine Ní Mhaolagáin", "Conor Mac Cárthaigh", "Niamh Ní Dhomhnaill"],
  is: ["Jón Jónsson", "Anna Sigurðardóttir", "Magnús Guðmundsson", "Sara Ólafsdóttir"],
  fa: ["علی محمدی", "سارا حسینی", "امیر رضایی", "نگین کریمی"],
  ar: ["محمد أحمد", "فاطمة علي", "خالد حسن", "ليلى إبراهيم"],
  ja: ["田中太郎", "鈴木花子", "佐藤健", "高橋美咲"],
  ko: ["김민준", "이서연", "박지훈", "최수아"],
  zh: ["王伟", "李娜", "张磊", "刘洋"],
};
