import type { CuisineKey } from "./cuisine";

/** Multilingual string. `en` is the canonical fallback; other locale keys may or may not exist.
 *  The seeder picks `[seedLocale]` and falls back to `en` when missing. */
export type LocaleString = { en: string } & Partial<Record<string, string>>;

export type SeedCategory = { sortOrder: number; name: LocaleString };

export type SeedItem = {
  categoryIndex: number;
  sortOrder: number;
  price: number;
  name: LocaleString;
  description?: LocaleString;
  /** Direct S3 URL — reused from the previously generated template image set. */
  imageUrl?: string;
};

export type CuisineTemplate = {
  subtitle: LocaleString;
  categories: SeedCategory[];
  items: SeedItem[];
  /** Restaurant cover background. */
  backgroundUrl?: string;
};

const COMMON_PLACEHOLDERS = {
  description: {
    en: "Replace this with your own description",
    es: "Reemplaza esto con tu descripción",
    de: "Ersetze dies durch deine eigene Beschreibung",
    fr: "Remplace ceci par ta propre description",
    it: "Sostituisci con la tua descrizione",
    pt: "Substitui por tua descrição",
    nl: "Vervang dit door je eigen beschrijving",
    pl: "Zastąp to własnym opisem",
    ru: "Замени это своим описанием",
    uk: "Заміни це своїм описом",
    sv: "Ersätt detta med din egen beskrivning",
    da: "Erstat dette med din egen beskrivelse",
    no: "Erstatt dette med din egen beskrivelse",
    fi: "Korvaa tämä omalla kuvauksellasi",
    cs: "Nahraď to vlastním popisem",
    el: "Αντικαταστήστε με τη δική σας περιγραφή",
    tr: "Bunu kendi açıklamanla değiştir",
    ro: "Înlocuiește cu propria descriere",
    hu: "Cseréld le saját leírásra",
    bg: "Замени това със собственото си описание",
    hr: "Zamijeni vlastitim opisom",
    sk: "Nahraď vlastným popisom",
    sl: "Zamenjaj s svojim opisom",
    et: "Asenda oma kirjeldusega",
    lv: "Aizstāj ar savu aprakstu",
    lt: "Pakeisk savo aprašymu",
    sr: "Zameni sopstvenim opisom",
    ca: "Substitueix per la teva descripció",
    ga: "Athchuir é seo le do thuairisc féin",
    is: "Skiptu þessu út fyrir þína eigin lýsingu",
    fa: "این را با توضیحات خودتان جایگزین کنید",
    ar: "استبدل هذا بوصفك الخاص",
    ja: "ここをあなたの説明に置き換えてください",
    ko: "이것을 자신의 설명으로 바꾸세요",
    zh: "将此处替换为您自己的描述",
  } as LocaleString,
  address: "Sample Street 1, Your City",
  phone: "+34 600 000 000",
  instagram: "your_restaurant",
  whatsapp: "+34600000000",
};

export const commonPlaceholders = COMMON_PLACEHOLDERS;

/** Default restaurant name applied to every brand-new account (onboarding is
 *  currently skipped, so the cuisine/name steps never run). Localized so the
 *  seeded restaurant reads naturally in the user's language. */
export const DEFAULT_RESTAURANT_NAME: LocaleString = {
  en: "My restaurant",
  es: "Mi restaurante",
  de: "Mein Restaurant",
  fr: "Mon restaurant",
  it: "Il mio ristorante",
  pt: "Meu restaurante",
  nl: "Mijn restaurant",
  pl: "Moja restauracja",
  ru: "Мой ресторан",
  uk: "Мій ресторан",
  sv: "Min restaurang",
  da: "Min restaurant",
  no: "Min restaurant",
  fi: "Ravintolani",
  cs: "Moje restaurace",
  el: "Το εστιατόριό μου",
  tr: "Restoranım",
  ro: "Restaurantul meu",
  hu: "Az éttermem",
  bg: "Моят ресторант",
  hr: "Moj restoran",
  sk: "Moja reštaurácia",
  sl: "Moja restavracija",
  et: "Minu restoran",
  lv: "Mans restorāns",
  lt: "Mano restoranas",
  sr: "Moj restoran",
  ca: "El meu restaurant",
  ga: "Mo bhialann",
  is: "Veitingastaðurinn minn",
  fa: "رستوران من",
  ar: "مطعمي",
  ja: "マイレストラン",
  ko: "내 레스토랑",
  zh: "我的餐厅",
};

/** Single universal template. Two categories (Food / Drinks), two items each.
 *  Food items carry a reused S3 photo; drinks intentionally have no image. */
export const cuisineTemplates: Record<CuisineKey, CuisineTemplate> = {
  restaurant: {
    subtitle: {
      en: "Fresh food & drinks",
      es: "Comida y bebidas frescas",
      de: "Frische Speisen & Getränke",
      fr: "Plats & boissons frais",
      it: "Cibo e bevande freschi",
      pt: "Comida e bebidas frescas",
      nl: "Vers eten & drinken",
      pl: "Świeże jedzenie i napoje",
      ru: "Свежая еда и напитки",
      uk: "Свіжа їжа та напої",
      sv: "Färsk mat & dryck",
      da: "Frisk mad & drikke",
      no: "Fersk mat og drikke",
      fi: "Tuoretta ruokaa ja juomaa",
      cs: "Čerstvé jídlo a nápoje",
      el: "Φρέσκο φαγητό & ποτά",
      tr: "Taze yemek & içecek",
      ro: "Mâncare și băuturi proaspete",
      hu: "Friss ételek és italok",
      bg: "Прясна храна и напитки",
      hr: "Svježa hrana i pića",
      sk: "Čerstvé jedlo a nápoje",
      sl: "Sveža hrana in pijača",
      et: "Värske toit ja joogid",
      lv: "Svaigs ēdiens un dzērieni",
      lt: "Šviežias maistas ir gėrimai",
      sr: "Sveža hrana i pića",
      ca: "Menjar i begudes fresques",
      ga: "Bia & deochanna úra",
      is: "Ferskur matur og drykkir",
      fa: "غذا و نوشیدنی تازه",
      ar: "طعام ومشروبات طازجة",
      ja: "新鮮な料理とドリンク",
      ko: "신선한 음식과 음료",
      zh: "新鲜美食与饮品",
    },
    categories: [
      {
        sortOrder: 1,
        name: {
          en: "Food",
          es: "Comida",
          de: "Speisen",
          fr: "Plats",
          it: "Cibo",
          pt: "Comida",
          nl: "Eten",
          pl: "Jedzenie",
          ru: "Еда",
          uk: "Їжа",
          sv: "Mat",
          da: "Mad",
          no: "Mat",
          fi: "Ruoka",
          cs: "Jídlo",
          el: "Φαγητό",
          tr: "Yemek",
          ro: "Mâncare",
          hu: "Ételek",
          bg: "Храна",
          hr: "Hrana",
          sk: "Jedlo",
          sl: "Hrana",
          et: "Toit",
          lv: "Ēdiens",
          lt: "Maistas",
          sr: "Hrana",
          ca: "Menjar",
          ga: "Bia",
          is: "Matur",
          fa: "غذا",
          ar: "طعام",
          ja: "料理",
          ko: "음식",
          zh: "美食",
        },
      },
      {
        sortOrder: 2,
        name: {
          en: "Drinks",
          es: "Bebidas",
          de: "Getränke",
          fr: "Boissons",
          it: "Bevande",
          pt: "Bebidas",
          nl: "Dranken",
          pl: "Napoje",
          ru: "Напитки",
          uk: "Напої",
          sv: "Drycker",
          da: "Drikkevarer",
          no: "Drikke",
          fi: "Juomat",
          cs: "Nápoje",
          el: "Ποτά",
          tr: "İçecekler",
          ro: "Băuturi",
          hu: "Italok",
          bg: "Напитки",
          hr: "Pića",
          sk: "Nápoje",
          sl: "Pijače",
          et: "Joogid",
          lv: "Dzērieni",
          lt: "Gėrimai",
          sr: "Pića",
          ca: "Begudes",
          ga: "Deochanna",
          is: "Drykkir",
          fa: "نوشیدنی‌ها",
          ar: "مشروبات",
          ja: "ドリンク",
          ko: "음료",
          zh: "饮品",
        },
      },
    ],
    items: [
      {
        categoryIndex: 0,
        sortOrder: 1,
        price: 9.5,
        imageUrl: "https://nbg1.your-objectstorage.com/sobogd/templates/dishes/dish-burger-classic-cheeseburger-opt2.webp",
        name: {
          en: "Cheeseburger",
          es: "Hamburguesa con queso",
          de: "Cheeseburger",
          fr: "Cheeseburger",
          it: "Cheeseburger",
          pt: "Cheeseburger",
          nl: "Cheeseburger",
          pl: "Cheeseburger",
          ru: "Чизбургер",
          uk: "Чизбургер",
          sv: "Cheeseburgare",
          da: "Cheeseburger",
          no: "Cheeseburger",
          fi: "Juustohampurilainen",
          cs: "Cheeseburger",
          el: "Τσίζμπεργκερ",
          tr: "Çizburger",
          ro: "Cheeseburger",
          hu: "Sajtburger",
          bg: "Чийзбургер",
          hr: "Cheeseburger",
          sk: "Cheeseburger",
          sl: "Čizburger",
          et: "Juustuburger",
          lv: "Siera burgers",
          lt: "Sūrio mėsainis",
          sr: "Čizburger",
          ca: "Hamburguesa amb formatge",
          ga: "Cáisbhorgaire",
          is: "Ostborgari",
          fa: "چیزبرگر",
          ar: "تشيزبرغر",
          ja: "チーズバーガー",
          ko: "치즈버거",
          zh: "芝士汉堡",
        },
      },
      {
        categoryIndex: 0,
        sortOrder: 2,
        price: 8.5,
        imageUrl: "https://nbg1.your-objectstorage.com/sobogd/templates/dishes/dish-restaurant-caesar-salad-opt2.webp",
        name: {
          en: "Caesar Salad",
          es: "Ensalada César",
          de: "Caesar Salat",
          fr: "Salade César",
          it: "Insalata Caesar",
          pt: "Salada Caesar",
          nl: "Caesarsalade",
          pl: "Sałatka Cezar",
          ru: "Салат «Цезарь»",
          uk: "Салат «Цезар»",
          sv: "Caesarsallad",
          da: "Cæsarsalat",
          no: "Cæsarsalat",
          fi: "Caesar-salaatti",
          cs: "Caesar salát",
          el: "Σαλάτα του Καίσαρα",
          tr: "Sezar Salatası",
          ro: "Salată Caesar",
          hu: "Cézár saláta",
          bg: "Салата «Цезар»",
          hr: "Cezar salata",
          sk: "Caesar šalát",
          sl: "Cezar solata",
          et: "Caesari salat",
          lv: "Cēzara salāti",
          lt: "Cezario salotos",
          sr: "Cezar salata",
          ca: "Amanida Cèsar",
          ga: "Sailéad Caesar",
          is: "Caesar salat",
          fa: "سالاد سزار",
          ar: "سلطة سيزر",
          ja: "シーザーサラダ",
          ko: "시저 샐러드",
          zh: "凯撒沙拉",
        },
      },
      {
        categoryIndex: 1,
        sortOrder: 1,
        price: 3.5,
        name: {
          en: "Orange Juice",
          es: "Zumo de naranja",
          de: "Orangensaft",
          fr: "Jus d'orange",
          it: "Succo d'arancia",
          pt: "Sumo de laranja",
          nl: "Sinaasappelsap",
          pl: "Sok pomarańczowy",
          ru: "Апельсиновый сок",
          uk: "Апельсиновий сік",
          sv: "Apelsinjuice",
          da: "Appelsinjuice",
          no: "Appelsinjuice",
          fi: "Appelsiinimehu",
          cs: "Pomerančový džus",
          el: "Χυμός πορτοκάλι",
          tr: "Portakal suyu",
          ro: "Suc de portocale",
          hu: "Narancslé",
          bg: "Портокалов сок",
          hr: "Sok od naranče",
          sk: "Pomarančový džús",
          sl: "Pomarančni sok",
          et: "Apelsinimahl",
          lv: "Apelsīnu sula",
          lt: "Apelsinų sultys",
          sr: "Sok od pomorandže",
          ca: "Suc de taronja",
          ga: "Sú oráiste",
          is: "Appelsínusafi",
          fa: "آب پرتقال",
          ar: "عصير برتقال",
          ja: "オレンジジュース",
          ko: "오렌지 주스",
          zh: "橙汁",
        },
      },
      {
        categoryIndex: 1,
        sortOrder: 2,
        price: 2.8,
        name: {
          en: "Cappuccino",
          es: "Cappuccino",
          de: "Cappuccino",
          fr: "Cappuccino",
          it: "Cappuccino",
          pt: "Cappuccino",
          nl: "Cappuccino",
          pl: "Cappuccino",
          ru: "Капучино",
          uk: "Капучино",
          sv: "Cappuccino",
          da: "Cappuccino",
          no: "Cappuccino",
          fi: "Cappuccino",
          cs: "Cappuccino",
          el: "Καπουτσίνο",
          tr: "Kapuçino",
          ro: "Cappuccino",
          hu: "Cappuccino",
          bg: "Капучино",
          hr: "Cappuccino",
          sk: "Cappuccino",
          sl: "Cappuccino",
          et: "Kaputsiino",
          lv: "Kapučīno",
          lt: "Kapučino",
          sr: "Cappuccino",
          ca: "Cappuccino",
          ga: "Cappuccino",
          is: "Cappuccino",
          fa: "کاپوچینو",
          ar: "كابتشينو",
          ja: "カプチーノ",
          ko: "카푸치노",
          zh: "卡布奇诺",
        },
      },
    ],
    backgroundUrl: "https://nbg1.your-objectstorage.com/sobogd/templates/backgrounds/bg-restaurant-opt2.webp",
  },
};

// Pool of realistic guest names per locale, used to populate sample orders/reservations.
// Locales not listed fall back to "en" in the seeder.
export const sampleGuestNames: Record<string, string[]> = {
  en: ["John Smith", "Sarah Johnson", "Michael Brown", "Emma Davis", "David Wilson", "Olivia Taylor"],
  es: ["María García", "Carlos López", "Laura Martínez", "Javier Rodríguez", "Sofía Fernández", "Diego Ruiz"],
  de: ["Anna Müller", "Lukas Schmidt", "Sophie Weber", "Maximilian Fischer"],
  fr: ["Pierre Dubois", "Marie Lefèvre", "Julien Bernard", "Camille Moreau"],
  it: ["Giulia Rossi", "Marco Bianchi", "Chiara Russo", "Lorenzo Ferrari"],
  pt: ["João Silva", "Mariana Santos", "Pedro Costa", "Ana Oliveira"],
  nl: ["Jan de Vries", "Emma Bakker", "Lars Visser", "Sophie Jansen"],
  pl: ["Anna Kowalska", "Piotr Nowak", "Maria Wiśniewska", "Tomasz Wójcik"],
  ru: ["Иван Иванов", "Анна Петрова", "Дмитрий Смирнов", "Екатерина Соколова"],
  uk: ["Олександр Шевченко", "Олена Коваленко", "Андрій Мельник", "Наталія Бондар"],
  sv: ["Erik Andersson", "Anna Karlsson", "Lars Johansson", "Maja Lindberg"],
  da: ["Mads Nielsen", "Sofie Hansen", "Lars Pedersen", "Emma Larsen"],
  no: ["Lars Hansen", "Ingrid Olsen", "Erik Berg", "Emma Solberg"],
  fi: ["Mikko Korhonen", "Anna Virtanen", "Jukka Mäkinen", "Liisa Nieminen"],
  cs: ["Jan Novák", "Eva Svobodová", "Petr Dvořák", "Tereza Černá"],
  el: ["Γιώργος Παπαδόπουλος", "Ελένη Δημητρίου", "Νίκος Γεωργίου", "Μαρία Ιωάννου"],
  tr: ["Mehmet Yılmaz", "Ayşe Demir", "Ali Kaya", "Zeynep Çelik"],
  ro: ["Andrei Popescu", "Maria Ionescu", "Mihai Stan", "Elena Dumitrescu"],
  hu: ["Péter Nagy", "Anna Kovács", "István Tóth", "Eszter Szabó"],
  bg: ["Иван Петров", "Мария Иванова", "Георги Димитров", "Елена Стоянова"],
  hr: ["Ivan Horvat", "Ana Marić", "Marko Novak", "Petra Kovačević"],
  sk: ["Ján Novák", "Mária Kováčová", "Peter Horváth", "Zuzana Tóthová"],
  sl: ["Janez Novak", "Maja Kovač", "Luka Horvat", "Eva Krajnc"],
  et: ["Andres Tamm", "Kati Saar", "Toomas Mägi", "Liis Kask"],
  lv: ["Jānis Bērziņš", "Anna Liepa", "Pēteris Kalniņš", "Līga Ozola"],
  lt: ["Jonas Petraitis", "Eglė Kazlauskienė", "Tomas Jankauskas", "Rūta Stankevičiūtė"],
  sr: ["Marko Petrović", "Ana Jovanović", "Stefan Nikolić", "Jelena Đorđević"],
  ca: ["Jordi Puig", "Núria Vila", "Marc Soler", "Anna Roca"],
  ga: ["Seán Ó Briain", "Áine Ní Mhaolagáin", "Conor Mac Cárthaigh", "Niamh Ní Dhomhnaill"],
  is: ["Jón Jónsson", "Anna Sigurðardóttir", "Magnús Guðmundsson", "Sara Ólafsdóttir"],
  fa: ["علی محمدی", "سارا حسینی", "امیر رضایی", "نگین کریمی"],
  ar: ["محمد أحمد", "فاطمة علي", "خالد حسن", "ليلى إبراهيم"],
  ja: ["田中太郎", "鈴木花子", "佐藤健", "高橋美咲"],
  ko: ["김민준", "이서연", "박지훈", "최수아"],
  zh: ["王伟", "李娜", "张磊", "刘洋"],
};
