// Setup-incomplete reminder — sent manually from the admin panel to nudge an
// owner who started setting up their restaurant on IQ Rest (menu, tables/QR,
// online orders, reservations, kitchen display) but didn't finish, while the
// trial is still running. Deliberately plain, transactional tone (no urgency,
// no "free") to keep spam score low. Greeting is name-less (many owners never
// set a restaurant title). CTA button + a reply are the two actions. {cta} is
// the dashboard-button label; the URL is injected by MailService.

interface T {
  subject: string;
  greeting: string;
  body: string;
  cta: string;
  help: string;
  closing: string;
  signature: string;
}

export const MENU_ALMOST_READY: Record<string, T> = {
  ar: {
    subject: "مطعمك على IQ Rest لم يكتمل إعداده بعد",
    greeting: "مرحبًا،",
    body: "بدأت إعداد مطعمك على IQ Rest لكنك لم تنهِه بعد. لكي تفتح قائمتك للضيوف، يكفي أن تضيف أطباقك، وتُعد الطاولات ورمز QR، وإن رغبت — الطلبات أونلاين والحجوزات وشاشة المطبخ. وصولك التجريبي مُفعّل بالفعل.",
    cta: "متابعة الإعداد",
    help: "إن واجهتك أي أسئلة أثناء الإعداد، فقط رد على هذا البريد وسأساعدك.",
    closing: "يسعدني مساعدتك على إكمال الإعداد.",
    signature: "مع أطيب التحيات،<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  bg: {
    subject: "Ресторантът ти в IQ Rest още не е настроен докрай",
    greeting: "Здравей,",
    body: "Започна да настройваш ресторанта си в IQ Rest, но още не си приключил. За да отвориш менюто за гостите, остава да добавиш ястията, да настроиш масите и QR кода, а при желание — онлайн поръчки, резервации и кухненски екран. Пробният ти достъп вече е активен.",
    cta: "Продължи настройката",
    help: "Ако възникнат въпроси по настройката, просто отговори на този имейл — ще ти помогна.",
    closing: "С радост ще ти помогна да завършиш настройката.",
    signature: "С уважение,<br>Богдан<br>IQ Rest | iq-rest.com",
  },
  ca: {
    subject: "El teu restaurant a IQ Rest encara no està configurat del tot",
    greeting: "Hola,",
    body: "Has començat a configurar el teu restaurant a IQ Rest però encara no ho has acabat. Per obrir la carta als clients només cal afegir els plats, configurar les taules i el codi QR i, si vols, les comandes en línia, les reserves i la pantalla de cuina. El teu accés de prova ja està actiu.",
    cta: "Continuar la configuració",
    help: "Si et sorgeix algun dubte durant la configuració, només respon a aquest correu i t'ajudo.",
    closing: "Estaré encantat d'ajudar-te a acabar la configuració.",
    signature: "Salutacions,<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  cs: {
    subject: "Vaše restaurace na IQ Rest ještě není plně nastavená",
    greeting: "Dobrý den,",
    body: "Začali jste nastavovat svou restauraci na IQ Rest, ale ještě jste neskončili. Abyste menu otevřeli hostům, stačí přidat jídla, nastavit stoly a QR kód a podle potřeby i online objednávky, rezervace a kuchyňskou obrazovku. Zkušební přístup už máte aktivní.",
    cta: "Pokračovat v nastavení",
    help: "Pokud při nastavení narazíte na otázky, stačí odpovědět na tento e-mail — rád pomůžu.",
    closing: "Rád vám pomůžu nastavení dokončit.",
    signature: "S pozdravem,<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  da: {
    subject: "Din restaurant på IQ Rest er ikke sat helt op endnu",
    greeting: "Hej,",
    body: "Du er begyndt at sætte din restaurant op på IQ Rest, men er ikke færdig endnu. For at åbne menuen for gæsterne skal du bare tilføje dine retter, sætte borde og QR-koden op og — hvis du vil — onlinebestilling, reservationer og køkkenskærmen. Din prøveadgang er allerede aktiv.",
    cta: "Fortsæt opsætningen",
    help: "Hvis der dukker spørgsmål op undervejs, så svar bare på denne e-mail — jeg hjælper gerne.",
    closing: "Jeg hjælper gerne med at gøre opsætningen færdig.",
    signature: "Venlig hilsen,<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  de: {
    subject: "Ihr Restaurant auf IQ Rest ist noch nicht fertig eingerichtet",
    greeting: "Hallo,",
    body: "Sie haben begonnen, Ihr Restaurant in IQ Rest einzurichten, sind aber noch nicht fertig. Um Ihre Speisekarte für Gäste zu öffnen, müssen Sie nur noch Ihre Gerichte hinzufügen, Tische und den QR-Code einrichten und bei Bedarf Online-Bestellungen, Reservierungen und den Küchenbildschirm. Ihr Testzugang ist bereits aktiv.",
    cta: "Einrichtung fortsetzen",
    help: "Wenn bei der Einrichtung Fragen auftauchen, antworten Sie einfach auf diese E-Mail — ich helfe Ihnen gern.",
    closing: "Ich helfe Ihnen gern, die Einrichtung abzuschließen.",
    signature: "Mit freundlichen Grüßen,<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  el: {
    subject: "Το εστιατόριό σου στο IQ Rest δεν έχει ρυθμιστεί πλήρως ακόμη",
    greeting: "Γεια σου,",
    body: "Ξεκίνησες να ρυθμίζεις το εστιατόριό σου στο IQ Rest αλλά δεν το ολοκλήρωσες ακόμη. Για να ανοίξεις το μενού στους πελάτες, μένει να προσθέσεις τα πιάτα, να ρυθμίσεις τα τραπέζια και τον κωδικό QR και, αν θέλεις, τις online παραγγελίες, τις κρατήσεις και την οθόνη κουζίνας. Η δοκιμαστική σου πρόσβαση είναι ήδη ενεργή.",
    cta: "Συνέχεια ρύθμισης",
    help: "Αν προκύψουν ερωτήσεις κατά τη ρύθμιση, απλώς απάντησε σε αυτό το email — θα σε βοηθήσω.",
    closing: "Με χαρά θα σε βοηθήσω να ολοκληρώσεις τη ρύθμιση.",
    signature: "Με εκτίμηση,<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  en: {
    subject: "Your restaurant on IQ Rest isn't set up yet",
    greeting: "Hi there,",
    body: "You started setting up your restaurant on IQ Rest but haven't finished yet. To open your menu to guests, you just need to add your dishes, set up tables and the QR code, and — if you want — online orders, reservations and the kitchen display. Your trial access is already active.",
    cta: "Continue setup",
    help: "If any questions come up while you're setting things up, just reply to this email — I'll help you sort it out.",
    closing: "Happy to help you finish the setup.",
    signature: "Best regards,<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  es: {
    subject: "Tu restaurante en IQ Rest aún no está configurado del todo",
    greeting: "Hola,",
    body: "Empezaste a configurar tu restaurante en IQ Rest pero aún no lo has terminado. Para abrir la carta a los clientes solo falta añadir tus platos, configurar las mesas y el código QR y, si quieres, los pedidos online, las reservas y la pantalla de cocina. Tu acceso de prueba ya está activo.",
    cta: "Continuar configuración",
    help: "Si te surge alguna duda durante la configuración, solo responde a este correo y te ayudo.",
    closing: "Estaré encantado de ayudarte a terminar la configuración.",
    signature: "Un saludo,<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  et: {
    subject: "Sinu restoran IQ Restis pole veel lõpuni seadistatud",
    greeting: "Tere,",
    body: "Alustasid oma restorani seadistamist IQ Restis, kuid pole veel lõpetanud. Menüü külalistele avamiseks tuleb veel lisada road, seadistada lauad ja QR-kood ning soovi korral veebitellimused, broneeringud ja köögiekraan. Sinu prooviligipääs on juba aktiivne.",
    cta: "Jätka seadistamist",
    help: "Kui seadistamisel tekib küsimusi, vasta lihtsalt sellele kirjale — aitan hea meelega.",
    closing: "Aitan hea meelega seadistuse lõpule viia.",
    signature: "Parimate soovidega,<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  fa: {
    subject: "رستوران شما در IQ Rest هنوز کامل تنظیم نشده است",
    greeting: "سلام،",
    body: "راه‌اندازی رستوران خود را در IQ Rest شروع کرده‌اید اما هنوز کامل نکرده‌اید. برای باز کردن منو برای مهمانان کافی است غذاها را اضافه کنید، میزها و کد QR را تنظیم کنید و در صورت تمایل سفارش آنلاین، رزرو و نمایشگر آشپزخانه را. دسترسی آزمایشی شما هم‌اکنون فعال است.",
    cta: "ادامه تنظیمات",
    help: "اگر هنگام تنظیم سؤالی پیش آمد، کافی است به این ایمیل پاسخ دهید تا کمکتان کنم.",
    closing: "خوشحال می‌شوم در تکمیل تنظیمات کمکتان کنم.",
    signature: "با احترام،<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  fi: {
    subject: "Ravintolasi IQ Restissä ei ole vielä valmiiksi määritetty",
    greeting: "Hei,",
    body: "Aloitit ravintolasi käyttöönoton IQ Restissä, mutta et ole vielä valmis. Jotta voit avata valikon vieraille, sinun tarvitsee vielä lisätä annokset, määrittää pöydät ja QR-koodi sekä halutessasi verkkotilaukset, varaukset ja keittiönäyttö. Kokeilukäyttösi on jo aktiivinen.",
    cta: "Jatka käyttöönottoa",
    help: "Jos käyttöönotossa herää kysymyksiä, vastaa vain tähän viestiin — autan mielelläni.",
    closing: "Autan mielelläni saamaan käyttöönoton valmiiksi.",
    signature: "Ystävällisin terveisin,<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  fr: {
    subject: "Votre restaurant sur IQ Rest n'est pas encore entièrement configuré",
    greeting: "Bonjour,",
    body: "Vous avez commencé à configurer votre restaurant sur IQ Rest mais vous n'avez pas encore terminé. Pour ouvrir votre menu aux clients, il reste à ajouter vos plats, configurer les tables et le code QR et, si vous le souhaitez, les commandes en ligne, les réservations et l'écran cuisine. Votre accès d'essai est déjà actif.",
    cta: "Continuer la configuration",
    help: "Si des questions surgissent pendant la configuration, répondez simplement à cet e-mail — je vous aiderai.",
    closing: "Je serai ravi de vous aider à terminer la configuration.",
    signature: "Cordialement,<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  ga: {
    subject: "Níl do bhialann ar IQ Rest socraithe go hiomlán fós",
    greeting: "Dia duit,",
    body: "Thosaigh tú ag cumrú do bhialainne ar IQ Rest ach níor chríochnaigh tú fós é. Chun do bhiachlár a oscailt do na haíonna, níl le déanamh ach na miasa a chur leis, na boird agus an cód QR a shocrú agus, más mian leat, orduithe ar líne, áirithintí agus an scáileán cistine. Tá do rochtain trialach gníomhach cheana.",
    cta: "Lean ar aghaidh leis an socrú",
    help: "Má bhíonn aon cheist agat le linn na cumraíochta, ní gá ach freagra a thabhairt ar an ríomhphost seo — cuideoidh mé leat.",
    closing: "Cuideoidh mé go fonnmhar leat an chumraíocht a chríochnú.",
    signature: "Le meas,<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  hr: {
    subject: "Tvoj restoran na IQ Rest još nije do kraja postavljen",
    greeting: "Pozdrav,",
    body: "Počeo si postavljati svoj restoran na IQ Rest, ali još nisi završio. Da bi otvorio jelovnik gostima, preostaje dodati jela, postaviti stolove i QR kod te, po želji, online narudžbe, rezervacije i kuhinjski ekran. Tvoj probni pristup već je aktivan.",
    cta: "Nastavi postavljanje",
    help: "Ako se tijekom postavljanja pojave pitanja, samo odgovori na ovaj e-mail — rado ću pomoći.",
    closing: "Rado ću ti pomoći dovršiti postavljanje.",
    signature: "Lijep pozdrav,<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  hu: {
    subject: "Az éttermed az IQ Resten még nincs teljesen beállítva",
    greeting: "Szia,",
    body: "Elkezdted beállítani az éttermedet az IQ Resten, de még nem fejezted be. Ahhoz, hogy megnyisd az étlapot a vendégeknek, már csak hozzá kell adnod az ételeket, beállítani az asztalokat és a QR-kódot, és ha szeretnéd, az online rendelést, a foglalásokat és a konyhai kijelzőt. A próbahozzáférésed már aktív.",
    cta: "Beállítás folytatása",
    help: "Ha a beállítás közben kérdés merül fel, csak válaszolj erre az e-mailre — szívesen segítek.",
    closing: "Szívesen segítek befejezni a beállítást.",
    signature: "Üdvözlettel,<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  is: {
    subject: "Veitingastaðurinn þinn á IQ Rest er ekki fullstilltur enn",
    greeting: "Halló,",
    body: "Þú byrjaðir að setja upp veitingastaðinn þinn á IQ Rest en hefur ekki klárað enn. Til að opna matseðilinn fyrir gesti þarftu aðeins að bæta við réttum, stilla borð og QR-kóða og, ef þú vilt, netpantanir, borðabókanir og eldhússkjáinn. Prufuaðgangurinn þinn er þegar virkur.",
    cta: "Halda áfram uppsetningu",
    help: "Ef einhverjar spurningar vakna við uppsetninguna, svaraðu bara þessum tölvupósti — ég hjálpa þér.",
    closing: "Ég hjálpa þér gjarnan að klára uppsetninguna.",
    signature: "Með bestu kveðjum,<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  it: {
    subject: "Il tuo ristorante su IQ Rest non è ancora configurato del tutto",
    greeting: "Ciao,",
    body: "Hai iniziato a configurare il tuo ristorante su IQ Rest ma non hai ancora finito. Per aprire il menu ai clienti basta aggiungere i piatti, configurare i tavoli e il codice QR e, se vuoi, gli ordini online, le prenotazioni e lo schermo cucina. Il tuo accesso di prova è già attivo.",
    cta: "Continua la configurazione",
    help: "Se ti vengono dubbi durante la configurazione, rispondi a questa email e ti aiuto.",
    closing: "Sarò felice di aiutarti a completare la configurazione.",
    signature: "Cordiali saluti,<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  ja: {
    subject: "IQ Rest のレストラン設定がまだ完了していません",
    greeting: "こんにちは。",
    body: "IQ Rest でのレストランの設定を始めていただきましたが、まだ完了していません。メニューをお客様に公開するには、料理を追加し、テーブルとQRコードを設定し、必要に応じてオンライン注文・予約・キッチンディスプレイを設定するだけです。トライアルはすでに有効になっています。",
    cta: "設定を続ける",
    help: "設定中にご不明な点があれば、このメールに返信してください。お手伝いします。",
    closing: "設定を最後まで進めるお手伝いをいたします。",
    signature: "敬具<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  ko: {
    subject: "IQ Rest의 식당 설정이 아직 완료되지 않았습니다",
    greeting: "안녕하세요,",
    body: "IQ Rest에서 식당 설정을 시작하셨지만 아직 끝내지 않으셨습니다. 메뉴를 손님에게 공개하시려면 메뉴 항목을 추가하고, 테이블과 QR 코드를 설정하고, 원하시면 온라인 주문, 예약, 주방 디스플레이를 설정하시면 됩니다. 체험 이용은 이미 활성화되어 있습니다.",
    cta: "설정 계속하기",
    help: "설정 중에 궁금한 점이 생기면 이 이메일에 답장만 주세요. 도와드리겠습니다.",
    closing: "설정을 끝까지 마치실 수 있도록 기꺼이 돕겠습니다.",
    signature: "감사합니다.<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  lt: {
    subject: "Jūsų restoranas IQ Rest dar nėra iki galo sukonfigūruotas",
    greeting: "Sveiki,",
    body: "Pradėjote kurti savo restoraną IQ Rest, bet dar nebaigėte. Kad atvertumėte meniu svečiams, belieka pridėti patiekalus, sukonfigūruoti stalus ir QR kodą ir, jei norite, internetinius užsakymus, rezervacijas bei virtuvės ekraną. Jūsų bandomoji prieiga jau aktyvi.",
    cta: "Tęsti konfigūravimą",
    help: "Jei konfigūruojant kils klausimų, tiesiog atsakykite į šį laišką — mielai padėsiu.",
    closing: "Mielai padėsiu užbaigti konfigūravimą.",
    signature: "Pagarbiai,<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  lv: {
    subject: "Jūsu restorāns IQ Rest vēl nav līdz galam iestatīts",
    greeting: "Sveiki,",
    body: "Sākāt iestatīt savu restorānu IQ Rest, bet vēl neesat pabeidzis. Lai atvērtu ēdienkarti viesiem, atliek pievienot ēdienus, iestatīt galdus un QR kodu un, ja vēlaties, tiešsaistes pasūtījumus, rezervācijas un virtuves ekrānu. Jūsu izmēģinājuma piekļuve jau ir aktīva.",
    cta: "Turpināt iestatīšanu",
    help: "Ja iestatīšanas laikā rodas jautājumi, vienkārši atbildiet uz šo e-pastu — labprāt palīdzēšu.",
    closing: "Labprāt palīdzēšu pabeigt iestatīšanu.",
    signature: "Ar cieņu,<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  nl: {
    subject: "Je restaurant op IQ Rest is nog niet helemaal ingesteld",
    greeting: "Hallo,",
    body: "Je bent begonnen met het instellen van je restaurant op IQ Rest, maar je bent nog niet klaar. Om je menu voor gasten te openen, hoef je alleen je gerechten toe te voegen, de tafels en de QR-code in te stellen en, als je wilt, online bestellingen, reserveringen en het keukenscherm. Je proeftoegang is al actief.",
    cta: "Configuratie voortzetten",
    help: "Als er tijdens het instellen vragen opkomen, antwoord dan gewoon op deze e-mail — ik help je graag.",
    closing: "Ik help je graag om de instellingen af te ronden.",
    signature: "Met vriendelijke groet,<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  no: {
    subject: "Restauranten din på IQ Rest er ikke ferdig satt opp ennå",
    greeting: "Hei,",
    body: "Du har begynt å sette opp restauranten din på IQ Rest, men er ikke ferdig ennå. For å åpne menyen for gjestene gjenstår det bare å legge til rettene, sette opp bord og QR-koden og, om du vil, nettbestilling, reservasjoner og kjøkkenskjermen. Prøvetilgangen din er allerede aktiv.",
    cta: "Fortsett oppsettet",
    help: "Hvis det dukker opp spørsmål underveis, bare svar på denne e-posten — jeg hjelper deg gjerne.",
    closing: "Jeg hjelper deg gjerne med å fullføre oppsettet.",
    signature: "Med vennlig hilsen,<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  pl: {
    subject: "Twoja restauracja w IQ Rest nie jest jeszcze w pełni skonfigurowana",
    greeting: "Cześć,",
    body: "Zacząłeś konfigurować swoją restaurację w IQ Rest, ale jeszcze nie skończyłeś. Aby otworzyć menu dla gości, wystarczy dodać dania, ustawić stoliki i kod QR oraz, jeśli chcesz, zamówienia online, rezerwacje i ekran kuchenny. Twój dostęp próbny jest już aktywny.",
    cta: "Kontynuuj konfigurację",
    help: "Jeśli podczas konfiguracji pojawią się pytania, po prostu odpowiedz na tę wiadomość — chętnie pomogę.",
    closing: "Chętnie pomogę dokończyć konfigurację.",
    signature: "Pozdrawiam,<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  pt: {
    subject: "O seu restaurante no IQ Rest ainda não está totalmente configurado",
    greeting: "Olá,",
    body: "Começou a configurar o seu restaurante no IQ Rest mas ainda não terminou. Para abrir o menu aos clientes, falta apenas adicionar os pratos, configurar as mesas e o código QR e, se quiser, os pedidos online, as reservas e o ecrã de cozinha. O seu acesso de teste já está ativo.",
    cta: "Continuar configuração",
    help: "Se surgir alguma dúvida durante a configuração, basta responder a este e-mail — terei todo o gosto em ajudar.",
    closing: "Terei todo o gosto em ajudá-lo a concluir a configuração.",
    signature: "Com os melhores cumprimentos,<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  ro: {
    subject: "Restaurantul tău pe IQ Rest nu este încă configurat complet",
    greeting: "Salut,",
    body: "Ai început să-ți configurezi restaurantul pe IQ Rest, dar încă nu ai terminat. Ca să deschizi meniul pentru clienți, mai rămâne să adaugi preparatele, să configurezi mesele și codul QR și, dacă vrei, comenzile online, rezervările și ecranul de bucătărie. Accesul tău de probă este deja activ.",
    cta: "Continuă configurarea",
    help: "Dacă apar întrebări în timpul configurării, doar răspunde la acest e-mail — te ajut cu plăcere.",
    closing: "Te ajut cu plăcere să finalizezi configurarea.",
    signature: "Cu stimă,<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  ru: {
    subject: "Ваш ресторан в IQ Rest ещё не настроен до конца",
    greeting: "Здравствуйте,",
    body: "Вы начали настраивать свой ресторан в IQ Rest, но пока не завершили. Чтобы открыть меню для гостей, осталось добавить блюда, настроить столы и QR-код, а при желании — онлайн-заказы, бронирования и кухонный экран. Пробный доступ у вас уже активен.",
    cta: "Продолжить настройку",
    help: "Если при настройке появятся вопросы, просто ответьте на это письмо — я помогу разобраться.",
    closing: "Буду рад помочь довести настройку до конца.",
    signature: "С уважением,<br>Богдан<br>IQ Rest | iq-rest.com",
  },
  sk: {
    subject: "Vaša reštaurácia na IQ Rest ešte nie je úplne nastavená",
    greeting: "Dobrý deň,",
    body: "Začali ste nastavovať svoju reštauráciu na IQ Rest, ale ešte ste neskončili. Aby ste menu otvorili hosťom, zostáva pridať jedlá, nastaviť stoly a QR kód a podľa potreby aj online objednávky, rezervácie a kuchynskú obrazovku. Skúšobný prístup už máte aktívny.",
    cta: "Pokračovať v nastavení",
    help: "Ak sa pri nastavovaní vyskytnú otázky, stačí odpovedať na tento e-mail — rád pomôžem.",
    closing: "Rád vám pomôžem nastavenie dokončiť.",
    signature: "S pozdravom,<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  sl: {
    subject: "Vaša restavracija na IQ Rest še ni do konca nastavljena",
    greeting: "Pozdravljeni,",
    body: "Začeli ste nastavljati svojo restavracijo na IQ Rest, vendar še niste končali. Da odprete jedilnik gostom, je treba le še dodati jedi, nastaviti mize in kodo QR ter po želji spletna naročila, rezervacije in kuhinjski zaslon. Vaš preizkusni dostop je že aktiven.",
    cta: "Nadaljuj nastavitev",
    help: "Če se med nastavljanjem pojavijo vprašanja, preprosto odgovorite na to sporočilo — z veseljem pomagam.",
    closing: "Z veseljem vam pomagam dokončati nastavitev.",
    signature: "Lep pozdrav,<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  sr: {
    subject: "Твој ресторан на IQ Rest још није до краја подешен",
    greeting: "Здраво,",
    body: "Почео си да подешаваш свој ресторан на IQ Rest, али још ниси завршио. Да би отворио мени гостима, остаје да додаш јела, подесиш столове и QR код и, по жељи, онлајн поруџбине, резервације и кухињски екран. Твој пробни приступ је већ активан.",
    cta: "Настави подешавање",
    help: "Ако се током подешавања појаве питања, само одговори на овај имејл — радо ћу помоћи.",
    closing: "Радо ћу ти помоћи да завршиш подешавање.",
    signature: "Срдачан поздрав,<br>Богдан<br>IQ Rest | iq-rest.com",
  },
  sv: {
    subject: "Din restaurang på IQ Rest är inte färdig att använda än",
    greeting: "Hej,",
    body: "Du har börjat ställa in din restaurang på IQ Rest men är inte klar än. För att öppna menyn för gästerna återstår bara att lägga till rätterna, ställa in bord och QR-koden och, om du vill, onlinebeställningar, bokningar och köksskärmen. Din provåtkomst är redan aktiv.",
    cta: "Fortsätt konfigurationen",
    help: "Om det dyker upp frågor när du ställer in, svara bara på det här mejlet — jag hjälper gärna till.",
    closing: "Jag hjälper gärna till att slutföra inställningen.",
    signature: "Vänliga hälsningar,<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  tr: {
    subject: "IQ Rest'teki restoranının kurulumu henüz tamamlanmadı",
    greeting: "Merhaba,",
    body: "Restoranını IQ Rest'te kurmaya başladın ama henüz bitirmedin. Menüyü misafirlere açmak için yemekleri eklemen, masaları ve QR kodu ayarlaman ve istersen online sipariş, rezervasyon ve mutfak ekranını kurman yeterli. Deneme erişimin zaten aktif.",
    cta: "Kuruluma devam et",
    help: "Kurulum sırasında soruların olursa bu e-postayı yanıtlaman yeterli — yardımcı olurum.",
    closing: "Kurulumu tamamlamana memnuniyetle yardımcı olurum.",
    signature: "Saygılarımla,<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  uk: {
    subject: "Ваш ресторан в IQ Rest ще не налаштований до кінця",
    greeting: "Вітаю,",
    body: "Ви почали налаштовувати свій ресторан в IQ Rest, але поки не завершили. Щоб відкрити меню для гостей, залишилося додати страви, налаштувати столи та QR-код, а за бажанням — онлайн-замовлення, бронювання та кухонний екран. Пробний доступ у вас уже активний.",
    cta: "Продовжити налаштування",
    help: "Якщо під час налаштування виникнуть запитання, просто відповідайте на цей лист — я допоможу розібратися.",
    closing: "Буду радий допомогти довести налаштування до кінця.",
    signature: "З повагою,<br>Богдан<br>IQ Rest | iq-rest.com",
  },
  zh: {
    subject: "您在 IQ Rest 的餐厅尚未设置完成",
    greeting: "您好,",
    body: "您已开始在 IQ Rest 设置餐厅,但还没有完成。要把菜单开放给客人,只需添加菜品、设置餐桌和 QR 码,如有需要再设置在线点单、预订和厨房显示屏即可。您的试用权限已经开通。",
    cta: "继续设置",
    help: "设置过程中如有任何疑问,直接回复这封邮件即可,我会帮您处理。",
    closing: "我很乐意帮您完成设置。",
    signature: "此致,<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
};

const RTL = new Set(["ar", "fa"]);
export function isRtl(locale: string): boolean {
  return RTL.has(locale);
}

export function pickMenuAlmostReady(locale: string): T {
  return MENU_ALMOST_READY[locale] || MENU_ALMOST_READY.en;
}
