// Trial-ending reminder — admin-triggered, sent ~1 day before the trial
// expires. Name-less by design (many owners never set a restaurant title). No
// price in copy — pricing differs per user; the CTA button (label {cta}, URL
// injected by MailService) sends them to the billing page where their own
// price is shown. Tone: helpful heads-up, not pushy.

interface T {
  subject: string;
  greeting: string;
  body: string;
  cta: string;
  help: string;
  closing: string;
  signature: string;
}

export const TRIAL_ENDING: Record<string, T> = {
  ar: {
    subject: "تجربتك في IQ Rest تنتهي غدًا",
    greeting: "مرحبًا،",
    body: "تذكير سريع: تجربتك المجانية في IQ Rest تنتهي غدًا. بعد ذلك، لن تكون قائمة QR متاحة لضيوفك حتى تختار خطة.",
    cta: "اختر خطة",
    help: "اختيار خطة لا يستغرق سوى لحظات. إذا كان لديك أي سؤال، فقط رد على هذا البريد.",
    closing: "شكرًا لتجربتك IQ Rest.",
    signature: "مع أطيب التحيات،<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  bg: {
    subject: "Пробният период на IQ Rest изтича утре",
    greeting: "Здравей,",
    body: "Малко напомняне: безплатният ти пробен период в IQ Rest изтича утре. След това QR менюто ти няма да е достъпно за гостите, докато не избереш план.",
    cta: "Избери план",
    help: "Изборът на план отнема само момент. Ако имаш въпроси, просто отговори на този имейл.",
    closing: "Благодаря, че опита IQ Rest.",
    signature: "С уважение,<br>Богдан<br>IQ Rest | iq-rest.com",
  },
  ca: {
    subject: "La teva prova d'IQ Rest acaba demà",
    greeting: "Hola,",
    body: "Petit recordatori: la teva prova gratuïta d'IQ Rest acaba demà. Després, el menú QR no estarà disponible per als clients fins que triïs un pla.",
    cta: "Triar un pla",
    help: "Triar un pla només porta un moment. Si tens cap pregunta, només respon a aquest correu.",
    closing: "Gràcies per provar IQ Rest.",
    signature: "Salutacions,<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  cs: {
    subject: "Vaše zkušební verze IQ Rest končí zítra",
    greeting: "Dobrý den,",
    body: "Krátká připomínka: vaše bezplatná zkušební verze IQ Rest končí zítra. Poté nebude QR menu dostupné pro vaše hosty, dokud nezvolíte tarif.",
    cta: "Vybrat tarif",
    help: "Výběr tarifu zabere jen chvilku. Pokud máte otázku, stačí odpovědět na tento e-mail.",
    closing: "Děkuji, že jste IQ Rest vyzkoušeli.",
    signature: "S pozdravem,<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  da: {
    subject: "Din IQ Rest-prøveperiode slutter i morgen",
    greeting: "Hej,",
    body: "Lille reminder: din gratis prøveperiode i IQ Rest slutter i morgen. Derefter vil QR-menuen ikke være tilgængelig for dine gæster, før du vælger en plan.",
    cta: "Vælg en plan",
    help: "Det tager kun et øjeblik at vælge en plan. Har du spørgsmål, svar bare på denne e-mail.",
    closing: "Tak fordi du prøvede IQ Rest.",
    signature: "Venlig hilsen,<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  de: {
    subject: "Deine IQ Rest-Testphase endet morgen",
    greeting: "Hallo,",
    body: "Kurze Erinnerung: Deine kostenlose Testphase bei IQ Rest endet morgen. Danach ist dein QR-Menü für deine Gäste nicht mehr verfügbar, bis du einen Tarif wählst.",
    cta: "Tarif wählen",
    help: "Einen Tarif zu wählen dauert nur einen Moment. Bei Fragen einfach auf diese E-Mail antworten.",
    closing: "Danke, dass du IQ Rest ausprobiert hast.",
    signature: "Beste Grüße,<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  el: {
    subject: "Η δοκιμαστική περίοδος του IQ Rest λήγει αύριο",
    greeting: "Γεια σου,",
    body: "Σύντομη υπενθύμιση: η δωρεάν δοκιμαστική περίοδος στο IQ Rest λήγει αύριο. Στη συνέχεια, το QR μενού σου δεν θα είναι διαθέσιμο στους πελάτες μέχρι να επιλέξεις πακέτο.",
    cta: "Επιλογή πακέτου",
    help: "Η επιλογή πακέτου παίρνει μόνο μια στιγμή. Αν έχεις απορίες, απλώς απάντησε σε αυτό το email.",
    closing: "Ευχαριστώ που δοκίμασες το IQ Rest.",
    signature: "Με εκτίμηση,<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  en: {
    subject: "Your IQ Rest trial ends tomorrow",
    greeting: "Hi there,",
    body: "Quick heads-up: your IQ Rest free trial ends tomorrow. After that, your QR menu won't be available to your guests until you pick a plan.",
    cta: "Choose a plan",
    help: "Picking a plan only takes a moment. If you have any questions, just reply to this email.",
    closing: "Thanks for trying IQ Rest.",
    signature: "Best regards,<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  es: {
    subject: "Tu prueba de IQ Rest termina mañana",
    greeting: "Hola,",
    body: "Recordatorio rápido: tu prueba gratuita de IQ Rest termina mañana. Después, tu menú QR no estará disponible para tus clientes hasta que elijas un plan.",
    cta: "Elegir un plan",
    help: "Elegir un plan solo lleva un momento. Si tienes alguna pregunta, solo responde a este correo.",
    closing: "Gracias por probar IQ Rest.",
    signature: "Saludos,<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  et: {
    subject: "Sinu IQ Rest prooviperiood lõpeb homme",
    greeting: "Tere,",
    body: "Lühike meeldetuletus: sinu tasuta prooviperiood IQ Restis lõpeb homme. Pärast seda ei ole QR-menüü külalistele saadaval, kuni valid paketi.",
    cta: "Vali pakett",
    help: "Paketi valimine võtab vaid hetke. Kui sul on küsimusi, lihtsalt vasta sellele e-kirjale.",
    closing: "Aitäh, et proovisid IQ Resti.",
    signature: "Lugupidamisega,<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  fa: {
    subject: "دوره آزمایشی IQ Rest شما فردا تمام می‌شود",
    greeting: "سلام،",
    body: "یادآوری سریع: دوره آزمایشی رایگان شما در IQ Rest فردا به پایان می‌رسد. پس از آن، منوی QR شما تا انتخاب یک پلن برای مهمانان در دسترس نخواهد بود.",
    cta: "انتخاب پلن",
    help: "انتخاب پلن فقط چند لحظه طول می‌کشد. اگر سوالی دارید، کافی است به این ایمیل پاسخ دهید.",
    closing: "ممنون که IQ Rest را امتحان کردید.",
    signature: "با احترام،<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  fi: {
    subject: "IQ Rest -kokeilujaksosi päättyy huomenna",
    greeting: "Hei,",
    body: "Pieni muistutus: ilmainen IQ Rest -kokeilujaksosi päättyy huomenna. Sen jälkeen QR-ruokalistasi ei ole vieraidesi saatavilla, ennen kuin valitset paketin.",
    cta: "Valitse paketti",
    help: "Paketin valitseminen vie vain hetken. Jos sinulla on kysyttävää, vastaa vain tähän sähköpostiin.",
    closing: "Kiitos, että kokeilit IQ Restia.",
    signature: "Ystävällisin terveisin,<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  fr: {
    subject: "Votre essai IQ Rest se termine demain",
    greeting: "Bonjour,",
    body: "Petit rappel : votre essai gratuit d'IQ Rest se termine demain. Après cela, votre menu QR ne sera plus accessible à vos clients tant que vous n'aurez pas choisi un forfait.",
    cta: "Choisir un forfait",
    help: "Choisir un forfait ne prend qu'un instant. Pour toute question, répondez simplement à cet e-mail.",
    closing: "Merci d'avoir essayé IQ Rest.",
    signature: "Cordialement,<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  ga: {
    subject: "Críochnóidh do thriail IQ Rest amárach",
    greeting: "Dia duit,",
    body: "Meabhrúchán tapa: críochnóidh do thriail saor in aisce IQ Rest amárach. Ina dhiaidh sin, ní bheidh do roghchlár QR ar fáil do d'aíonna go dtí go roghnóidh tú plean.",
    cta: "Roghnaigh plean",
    help: "Ní thógann sé ach nóiméad plean a roghnú. Má tá ceist agat, freagair an ríomhphost seo.",
    closing: "Go raibh maith agat as triail a bhaint as IQ Rest.",
    signature: "Le meas,<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  hr: {
    subject: "Tvoje IQ Rest probno razdoblje istječe sutra",
    greeting: "Pozdrav,",
    body: "Brzi podsjetnik: tvoje besplatno probno razdoblje u IQ Restu istječe sutra. Nakon toga QR jelovnik neće biti dostupan gostima dok ne odabereš plan.",
    cta: "Odaberi plan",
    help: "Odabir plana traje samo trenutak. Ako imaš pitanja, samo odgovori na ovaj email.",
    closing: "Hvala što si isprobao/la IQ Rest.",
    signature: "Pozdrav,<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  hu: {
    subject: "Az IQ Rest próbaidőszakod holnap lejár",
    greeting: "Szia,",
    body: "Gyors emlékeztető: az IQ Rest ingyenes próbaidőszakod holnap lejár. Ezután a QR menü nem lesz elérhető a vendégeid számára, amíg nem választasz csomagot.",
    cta: "Csomag választása",
    help: "A csomagválasztás csak egy pillanat. Ha kérdésed van, csak válaszolj erre az e-mailre.",
    closing: "Köszönöm, hogy kipróbáltad az IQ Restet.",
    signature: "Üdvözlettel,<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  is: {
    subject: "IQ Rest prufutímabilið þitt rennur út á morgun",
    greeting: "Halló,",
    body: "Stutt áminning: ókeypis prufutímabilið þitt í IQ Rest rennur út á morgun. Eftir það verður QR matseðillinn ekki tiltækur fyrir gesti þína fyrr en þú velur áskrift.",
    cta: "Velja áskrift",
    help: "Það tekur aðeins augnablik að velja áskrift. Ef þú hefur spurningar, svaraðu bara þessum tölvupósti.",
    closing: "Takk fyrir að prófa IQ Rest.",
    signature: "Bestu kveðjur,<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  it: {
    subject: "La tua prova di IQ Rest finisce domani",
    greeting: "Ciao,",
    body: "Promemoria veloce: la tua prova gratuita di IQ Rest finisce domani. Dopo, il menu QR non sarà più disponibile per i tuoi clienti finché non scegli un piano.",
    cta: "Scegli un piano",
    help: "Scegliere un piano richiede solo un attimo. Se hai domande, basta rispondere a questa email.",
    closing: "Grazie per aver provato IQ Rest.",
    signature: "Cordiali saluti,<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  ja: {
    subject: "IQ Rest の無料トライアルが明日終了します",
    greeting: "こんにちは。",
    body: "簡単なお知らせです：IQ Rest の無料トライアルが明日終了します。その後はプランを選ぶまで、QR メニューはお客様にご覧いただけなくなります。",
    cta: "プランを選ぶ",
    help: "プランの選択はほんの少しで終わります。ご質問があれば、このメールに返信してください。",
    closing: "IQ Rest をお試しいただきありがとうございます。",
    signature: "よろしくお願いいたします、<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  ko: {
    subject: "IQ Rest 무료 체험이 내일 종료됩니다",
    greeting: "안녕하세요,",
    body: "간단한 알림입니다: IQ Rest 무료 체험이 내일 종료됩니다. 이후에는 요금제를 선택하기 전까지 QR 메뉴를 손님들에게 제공할 수 없습니다.",
    cta: "요금제 선택",
    help: "요금제 선택은 잠깐이면 됩니다. 궁금한 점은 이 이메일에 회신해 주세요.",
    closing: "IQ Rest를 사용해 보셔서 감사합니다.",
    signature: "감사합니다,<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  lt: {
    subject: "Jūsų IQ Rest bandomasis laikotarpis baigiasi rytoj",
    greeting: "Sveiki,",
    body: "Trumpas priminimas: nemokamas IQ Rest bandomasis laikotarpis baigiasi rytoj. Po to QR meniu nebus prieinamas svečiams, kol nepasirinksite plano.",
    cta: "Pasirinkti planą",
    help: "Plano pasirinkimas užtrunka vos akimirką. Jei turite klausimų, tiesiog atsakykite į šį laišką.",
    closing: "Ačiū, kad išbandėte IQ Rest.",
    signature: "Pagarbiai,<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  lv: {
    subject: "Jūsu IQ Rest izmēģinājuma periods beidzas rīt",
    greeting: "Sveiki,",
    body: "Īss atgādinājums: jūsu bezmaksas IQ Rest izmēģinājuma periods beidzas rīt. Pēc tam QR ēdienkarte nebūs pieejama viesiem, kamēr neizvēlēsieties plānu.",
    cta: "Izvēlēties plānu",
    help: "Plāna izvēle aizņem tikai mirkli. Ja ir jautājumi, vienkārši atbildiet uz šo e-pastu.",
    closing: "Paldies, ka izmēģinājāt IQ Rest.",
    signature: "Ar cieņu,<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  nl: {
    subject: "Je IQ Rest-proefperiode eindigt morgen",
    greeting: "Hallo,",
    body: "Korte herinnering: je gratis IQ Rest-proefperiode eindigt morgen. Daarna is je QR-menu niet meer beschikbaar voor je gasten totdat je een abonnement kiest.",
    cta: "Kies een abonnement",
    help: "Een abonnement kiezen kost maar een momentje. Heb je vragen, beantwoord gewoon deze e-mail.",
    closing: "Bedankt dat je IQ Rest hebt geprobeerd.",
    signature: "Met vriendelijke groet,<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  no: {
    subject: "Din IQ Rest-prøveperiode slutter i morgen",
    greeting: "Hei,",
    body: "Liten påminnelse: din gratis prøveperiode i IQ Rest slutter i morgen. Etter det vil ikke QR-menyen være tilgjengelig for gjestene før du velger en plan.",
    cta: "Velg en plan",
    help: "Det tar bare et øyeblikk å velge en plan. Har du spørsmål, svar gjerne på denne e-posten.",
    closing: "Takk for at du prøvde IQ Rest.",
    signature: "Vennlig hilsen,<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  pl: {
    subject: "Twój okres próbny IQ Rest kończy się jutro",
    greeting: "Cześć,",
    body: "Szybkie przypomnienie: Twój darmowy okres próbny w IQ Rest kończy się jutro. Potem menu QR nie będzie dostępne dla gości, dopóki nie wybierzesz planu.",
    cta: "Wybierz plan",
    help: "Wybór planu zajmuje tylko chwilę. Jeśli masz pytania, po prostu odpowiedz na ten e-mail.",
    closing: "Dziękuję za wypróbowanie IQ Rest.",
    signature: "Pozdrawiam,<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  pt: {
    subject: "A tua experiência IQ Rest termina amanhã",
    greeting: "Olá,",
    body: "Um lembrete rápido: a tua experiência gratuita no IQ Rest termina amanhã. Depois disso, o menu QR não estará disponível para os clientes até escolheres um plano.",
    cta: "Escolher um plano",
    help: "Escolher um plano leva apenas um momento. Se tiveres dúvidas, basta responder a este email.",
    closing: "Obrigado por experimentares o IQ Rest.",
    signature: "Cumprimentos,<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  ro: {
    subject: "Perioada de probă IQ Rest se încheie mâine",
    greeting: "Salut,",
    body: "Un reminder rapid: perioada gratuită de probă IQ Rest se încheie mâine. După aceea, meniul QR nu va fi disponibil pentru clienți până când alegi un plan.",
    cta: "Alege un plan",
    help: "Alegerea unui plan durează doar o clipă. Dacă ai întrebări, răspunde la acest e-mail.",
    closing: "Mulțumesc că ai încercat IQ Rest.",
    signature: "Cu stimă,<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  ru: {
    subject: "Пробный период IQ Rest заканчивается завтра",
    greeting: "Здравствуйте,",
    body: "Небольшое напоминание: ваш бесплатный пробный период в IQ Rest заканчивается завтра. После этого QR-меню будет недоступно гостям, пока вы не выберете тариф.",
    cta: "Выбрать тариф",
    help: "Выбор тарифа займёт всего минуту. Если есть вопросы, просто ответьте на это письмо.",
    closing: "Спасибо, что попробовали IQ Rest.",
    signature: "С уважением,<br>Богдан<br>IQ Rest | iq-rest.com",
  },
  sk: {
    subject: "Vaša skúšobná verzia IQ Rest končí zajtra",
    greeting: "Dobrý deň,",
    body: "Krátka pripomienka: vaša bezplatná skúšobná verzia IQ Rest končí zajtra. Potom nebude QR menu dostupné hosťom, kým nezvolíte plán.",
    cta: "Vybrať plán",
    help: "Výber plánu zaberie len chvíľu. Ak máte otázku, stačí odpovedať na tento e-mail.",
    closing: "Ďakujem, že ste si vyskúšali IQ Rest.",
    signature: "S pozdravom,<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  sl: {
    subject: "Tvoje preizkusno obdobje IQ Rest se konča jutri",
    greeting: "Pozdravljeni,",
    body: "Hiter opomnik: tvoje brezplačno preizkusno obdobje v IQ Rest se konča jutri. Nato QR meni gostom ne bo več na voljo, dokler ne izbereš naročnine.",
    cta: "Izberi naročnino",
    help: "Izbira naročnine vzame le trenutek. Če imaš vprašanja, samo odgovori na to e-pošto.",
    closing: "Hvala, da si preizkusil/a IQ Rest.",
    signature: "Lep pozdrav,<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  sr: {
    subject: "Твој IQ Rest пробни период истиче сутра",
    greeting: "Здраво,",
    body: "Кратак подсетник: твој бесплатни пробни период у IQ Rest-у истиче сутра. После тога QR мени неће бити доступан гостима док не одабереш план.",
    cta: "Изабери план",
    help: "Одабир плана траје само тренутак. Ако имаш питања, само одговори на овај имејл.",
    closing: "Хвала што си пробао/ла IQ Rest.",
    signature: "Поздрав,<br>Богдан<br>IQ Rest | iq-rest.com",
  },
  sv: {
    subject: "Din IQ Rest-provperiod tar slut imorgon",
    greeting: "Hej,",
    body: "Liten påminnelse: din gratis provperiod i IQ Rest tar slut imorgon. Därefter är QR-menyn inte tillgänglig för dina gäster förrän du väljer en plan.",
    cta: "Välj en plan",
    help: "Att välja en plan tar bara ett ögonblick. Har du frågor, svara bara på det här mejlet.",
    closing: "Tack för att du provade IQ Rest.",
    signature: "Vänliga hälsningar,<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  tr: {
    subject: "IQ Rest deneme süreniz yarın sona eriyor",
    greeting: "Merhaba,",
    body: "Kısa bir hatırlatma: IQ Rest ücretsiz deneme süreniz yarın sona eriyor. Sonrasında bir plan seçene kadar QR menünüz misafirleriniz için kullanılamayacak.",
    cta: "Plan seç",
    help: "Plan seçmek yalnızca bir dakikanızı alır. Sorunuz varsa bu e-postayı yanıtlamanız yeterli.",
    closing: "IQ Rest'i denediğiniz için teşekkürler.",
    signature: "Saygılarımla,<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
  uk: {
    subject: "Пробний період IQ Rest завершується завтра",
    greeting: "Вітаю,",
    body: "Невелике нагадування: ваш безкоштовний пробний період в IQ Rest завершується завтра. Після цього QR-меню буде недоступне гостям, поки ви не оберете тариф.",
    cta: "Обрати тариф",
    help: "Вибір тарифу займе лише хвилину. Якщо є питання, просто дайте відповідь на цей лист.",
    closing: "Дякую, що спробували IQ Rest.",
    signature: "З повагою,<br>Богдан<br>IQ Rest | iq-rest.com",
  },
  zh: {
    subject: "您的 IQ Rest 免费试用明天到期",
    greeting: "您好,",
    body: "简短提醒：您在 IQ Rest 的免费试用明天到期。之后，您的 QR 菜单将无法向客人展示，直到您选择一个套餐。",
    cta: "选择套餐",
    help: "选择套餐只需片刻。如果有任何问题,只需回复这封邮件即可。",
    closing: "感谢您试用 IQ Rest。",
    signature: "此致,<br>Bogdan<br>IQ Rest | iq-rest.com",
  },
};

const RTL = new Set(["ar", "fa"]);
export function isRtl(locale: string): boolean {
  return RTL.has(locale);
}

export function pickTrialEnding(locale: string): T {
  return TRIAL_ENDING[locale] || TRIAL_ENDING.en;
}
